# Programming for Data Analysis Assignment 2020

## Purpose of numpy.random package
The numpy.random package is used to generate numpy arrays of pseudo-random numbers, i.e., numbers which approximate randomly generated numbers but are generated using or non-random means[1]. These are innumerable applications for these numbers in science and mathematics. For instance, in machine learning one is often required to split data into train and test sets and the data has to be chosen randomly.

## Use of Simple random data and Permutations functions
### Simple random data
The Simple random data functions consist of the **integers**, **random**, **choice** and **bytes** functions[2]. 
#### Integers
**integers** returns a list of pseudo-random integers in a certain range and returns the list as a numpy array[3]. The range is defined by a low value and a high value input in the function. For instance, to generate a numpy array of 10 pseudo-random integers between 2 and 5:

In [55]:
from numpy.random import Generator, PCG64
rg = Generator(PCG64())
integer_list = rg.integers(low=2, high=5, size=10)

In [56]:
integer_list

array([2, 4, 4, 4, 4, 4, 4, 4, 3, 4], dtype=int64)

#### Random
**random**[4] performs a similar function to **integers** except it returns a numpy array of pseudo-random floats in a certain range rather than integers. For instance, to generate a numpy array of 10 pseudo-random floats between 2 and 5:

In [57]:
float_list = (5-2) *rg.random(10) + 2

In [58]:
float_list

array([2.57463289, 4.92973743, 4.44047221, 4.77711243, 4.23944523,
       4.92649441, 2.12819636, 4.48218573, 4.28445505, 4.8157619 ])

The max and min values for the **random** function are initially 0 and 1. To get floats between 2 and 5, you have to transform the data using the formula:<br> 
(b-a)rg.random(10) + a
where b is the max value of the range (5 in this instance), a is the min value in the range (2 in this instance)

#### Choice
**choice** selects a number of elements from a numpy array in a random order[5]. For instance, to randomly select 5 values from a numpy array of the first 10 numbers (0-9):

In [69]:
import numpy as np
ten_list = np.arange(10)
ten_list

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
rg.choice(ten_list, 5)

array([6, 2, 6, 4, 9])

#### Bytes
**bytes** returns a string of random bytes. For instance, to generate a string of 10 bytes:

In [62]:
rg.bytes(10)

b'\x1d\xc8X\x96\xea[@ph6'

### Permutations
#### Shuffle
**shuffle** rearranges an input numpy array randomly. The function does not return a value, instead it rearranges the input array "in-place" (i.e. the original input array is changed). For instance, to randomly rearrange a numpy array of the first 10 numbers (0-9):

In [83]:
ten_list = np.arange(10)
print(ten_list)
rg.shuffle(ten_list)
print(ten_list)

[0 1 2 3 4 5 6 7 8 9]
[3 5 8 2 4 7 1 9 6 0]


#### Permutation
**permutation** is very similar to **shuffle**, except that it does not rearrange the input array in-place, the original input array is unchanged. Instead, it returns a new numpy array which consists of randomly rearranged elements of the input array. For instance, to generate a numpy array of the randomy rearranged numpy array of the first 10 numbers (0-9):

In [82]:
ten_list = np.arange(10)
print(ten_list)
permuted = rg.permutation(ten_list)
print(permuted, ten_list)

[0 1 2 3 4 5 6 7 8 9]
[0 8 5 2 1 7 4 3 9 6] [0 1 2 3 4 5 6 7 8 9]
